version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    environment:
      ACCEPT_EULA: '1'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_PID: 'Developer'
      MSSQL_USER: 'SA'
    ports:
      - "1433:1433"
    networks:
      - sql_network

networks:
  sql_network:
    driver: bridge